/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SatelliteImage } from "./SatelliteImage";
import { SatelliteImageCountArgs } from "./SatelliteImageCountArgs";
import { SatelliteImageFindManyArgs } from "./SatelliteImageFindManyArgs";
import { SatelliteImageFindUniqueArgs } from "./SatelliteImageFindUniqueArgs";
import { DeleteSatelliteImageArgs } from "./DeleteSatelliteImageArgs";
import { SatelliteImageService } from "../satelliteImage.service";
@graphql.Resolver(() => SatelliteImage)
export class SatelliteImageResolverBase {
  constructor(protected readonly service: SatelliteImageService) {}

  async _satelliteImagesMeta(
    @graphql.Args() args: SatelliteImageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SatelliteImage])
  async satelliteImages(
    @graphql.Args() args: SatelliteImageFindManyArgs
  ): Promise<SatelliteImage[]> {
    return this.service.satelliteImages(args);
  }

  @graphql.Query(() => SatelliteImage, { nullable: true })
  async satelliteImage(
    @graphql.Args() args: SatelliteImageFindUniqueArgs
  ): Promise<SatelliteImage | null> {
    const result = await this.service.satelliteImage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SatelliteImage)
  async deleteSatelliteImage(
    @graphql.Args() args: DeleteSatelliteImageArgs
  ): Promise<SatelliteImage | null> {
    try {
      return await this.service.deleteSatelliteImage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
